version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    ports:
      - "9092:9092"

  postgres-1:
    image: postgres:13
    environment:
      POSTGRES_USER: service1user
      POSTGRES_PASSWORD: service1pass
      POSTGRES_DB: service1db
    ports:
      - "5432:5432"

  postgres-2:
    image: postgres:13
    environment:
      POSTGRES_USER: service2user
      POSTGRES_PASSWORD: service2pass
      POSTGRES_DB: service2db
    ports:
      - "5433:5432"

  service-1:
    build: ./service-1
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres-1
      POSTGRES_PORT: 5432

  service-2:
    build: ./service-2
    ports:
      - "3001:3001"
    environment:
      POSTGRES_HOST: postgres-2
      POSTGRES_PORT: 5432

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./admin-frontend:/app
      - /app/node_modules
