apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: my-microservices
build:
  artifacts:
    - image: service-1
      context: service-1/
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: service-2
      context: service-2/
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/*.yml
